steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - FUNCTION_NAME
  - --region=FUNCTION_REGION
  - --source=.
  - --trigger-http
  - --runtime=RUNTIME
